name: mo_money_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  get_it: ^7.7.0
  equatable: ^2.0.5
  injectable: ^2.4.2
  auto_route: ^8.1.3
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  nonce: ^1.2.0
  connectivity: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.10
  bloc_test: ^9.1.7
  mockito: ^5.4.4
  injectable_generator: ^2.6.1
  auto_route_generator: ^8.0.0
  analyzer:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/home/
    - assets/login/
    - assets/messages/
    - assets/profile/
    - assets/shared/


